import os
import re
from datetime import datetime

REPORT_DIR = "reports"
INDEX_FILE = "index.html"

TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cliper News</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body { background-color: #f8f9fa; }
        .report-card { transition: transform 0.2s; }
        .report-card:hover { transform: translateY(-5px); box-shadow: 0 4px 15px rgba(0,0,0,0.1); }
        .date-badge { font-size: 0.8em; }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary mb-5">
        <div class="container">
            <a class="navbar-brand" href="#">🗞️ Cliper News</a>
            <span class="navbar-text text-white">Morty's Brain Dump</span>
        </div>
    </nav>

    <div class="container">
        <div class="row">
            <!-- REPORTS_GO_HERE -->
        </div>
    </div>

    <footer class="text-center py-4 text-muted mt-5">
        <small>Generated by Morty &bull; OpenClaw</small>
    </footer>
</body>
</html>
"""

def get_report_metadata(filepath):
    filename = os.path.basename(filepath)
    date_str = filename.split('.')[0] # default fallback
    title = filename
    
    # Try to extract date from filename (YYYY-MM-DD)
    match = re.search(r'(\d{4}-\d{2}-\d{2})', filename)
    if match:
        date_str = match.group(1)

    # Try to extract title from first line of markdown
    try:
        with open(filepath, 'r') as f:
            first_line = f.readline().strip()
            if first_line.startswith('# '):
                title = first_line[2:]
    except:
        pass
        
    return {
        "file": filepath,
        "date": date_str,
        "title": title
    }

def generate():
    reports = []
    if os.path.exists(REPORT_DIR):
        files = sorted(os.listdir(REPORT_DIR), reverse=True)
        for f in files:
            if f.endswith(".md"):
                reports.append(get_report_metadata(os.path.join(REPORT_DIR, f)))
    
    html_cards = ""
    for r in reports:
        html_cards += f"""
            <div class="col-md-6 mb-4">
                <div class="card h-100 report-card">
                    <div class="card-body">
                        <div class="d-flex justify-content-between mb-2">
                            <span class="badge bg-info text-dark date-badge">{r['date']}</span>
                        </div>
                        <h5 class="card-title"><a href="{r['file']}" class="text-decoration-none text-dark stretched-link">{r['title']}</a></h5>
                        <p class="card-text text-muted">Click to read full report.</p>
                    </div>
                </div>
            </div>
        """
        
    final_html = TEMPLATE.replace("<!-- REPORTS_GO_HERE -->", html_cards)
    
    with open(INDEX_FILE, "w") as f:
        f.write(final_html)
    
    print(f"Generated {INDEX_FILE} with {len(reports)} reports.")

if __name__ == "__main__":
    generate()
